version: '3.12'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
        - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
        - .env
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

  api:
    image: arthurdedeus/gifts-api:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - minio
    build:
      context: .
    volumes:
      - .:/usr/src/app/
      - ./.tmp/static/:/tmp/static
      - ./.tmp/media/:/tmp/media

volumes:
  postgres_data:
  minio_data:
