version: '3.11'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DB_NAME=gifts-api-db
      - DB_USER=gifts-api
      - DB_PASSWORD=badaras
      - DB_HOST=db
      - DB_PORT=5432
      - PGDATA=/var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
