# Generated by Django 5.0.2 on 2024-03-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0002_create_checkout_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1)),
                ("total", models.IntegerField()),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="checkout_items",
                        to="gifts.checkout",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="gifts.gift"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
