# Generated by Django 5.0.2 on 2024-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0003_create_checkoutitem_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="message",
            field=models.TextField(
                blank=True, help_text="Message written by the gifter", null=True
            ),
        ),
    ]
