version: '3.11'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gifts-api-db
      - POSTGRES_USER=gifts-api
      - POSTGRES_PASSWORD=badaras
      - PGDATA=/var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - prod.env
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

  api-prod:
    command: ["poetry", "run", "gunicorn", "-b", "0.0.0.0:8000", "settings.wsgi"]
    build:
      context: ..
    volumes:
      - .:/usr/src/app/
      - ./.tmp/static/:/tmp/static
      - ./.tmp/media/:/tmp/media
    ports:
      - 8000:8000
    depends_on:
      - db
      - minio 
    env_file:
      - prod.env

volumes:
  postgres_data:
  minio_data:
