name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - '*'  # Trigger for any tag push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures you fetch all history for all tags and branches

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # Uses the tag name for the Docker image tag
          tags: arthurdedeus/gifts-api:${{ github.ref_name }}
